var restify = require('restify');
var errors  = require('restify-errors');
var path = require('path');

var server_name = 'web_server';
var server_version = '1.0.0';

const server = restify.createServer({name: server_name, version: server_version});
server.use(restify.plugins.acceptParser(server.acceptable));
server.use(restify.plugins.queryParser());
server.use(restify.plugins.bodyParser({ mapParams: true }));
server.use(restify.plugins.acceptParser(server.acceptable));

function renderError(error) { return new errors.InternalError(error); }
function renderMessage(msg) { return {'message': msg}; }
function handleError(next, error) {
    console.error(error);
    if (error instanceof ReferenceError) {
        return next(new errors.BadRequestError(error.message));
    }
    return next(renderError(error.message));
}

server.post('/ding',
            function (req, res, next) {
                res.send(renderMessage('dong'));
            });

server.post('/generate_error',
            function (req, res, next) {
                return next(new errors.InternalServerError("I am error generated by demand."));
            });

console.log('WEB Server starting')
var WebeServer = {
    start: function(port) {
        server.listen(port, '127.0.0.1', function () {
            console.log('%s listening at %s' , server.name, server.url);
        });
    },
}

module.exports = WebeServer;
